name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install LTTng
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:lttng/stable-2.13
          sudo apt-get update
          sudo apt-get install -y python3-babeltrace python3-lttng python3-bt2
        shell: bash

      - name: Install test packages
        run: |
          . /opt/ros/humble/setup.sh
          rosdep update
          rosdep install -r -y --from-paths .
        shell: bash

      # - name: Clone dependency packages
      #   run: |
      #     mkdir -p dependency_ws
      #     vcs import dependency_ws < build_depends.repos
      #     cd dependency_ws/CARET_analyze
      #     export PYTHONPATH=$PWD
      #     echo $PYTHONPATH
      #     touch AMENT_IGNORE
      #     cd ../../
      #   shell: bash

      - name: Install dependent packages
        run: python3 -m pip install -r requirements.txt

      - name: Run pytest
        run: |
          . /opt/ros/humble/setup.sh
          python3 -m pytest
